### ISSUE TITLE
Non-supplied but Non-required fields are still added in call 

### ISSUE THREAD

**Issue by Ton-O** [JavaWiz1/kodi-cli#1] opened 2022-07-10 11:51 UTC
Great work, thanks!
I've noticed that the project has knowledge on which fields are optional for a call.
However, the jsonrpc call fails when you do not supply the optional fields.
Example:
See syntax and required fields:
python kodi_cli.py -H 127.0.0.1 -P 8080 AddOns.GetAddons help

————————————————————————————————————————————————————————————————————————————————
Signature   : AddOns.GetAddons([type], [content], [enabled], [properties], [limits], [installed])
Description : Gets all available addons
————————————————————————————————————————————————————————————————————————————————
type
   Type     : String
   Required : False
   Reference: Addon.Types
   Default  : unknown
content
   Desc     : Content provided by the addon. Only considered for plugins and scripts.
   Type     : String
   Required : False
   Reference: Addon.Content
   Default  : unknown
enabled
   Type     : string|boolean
   Required : False
   Values   : True,False,all
   Default  : all
properties
   Type     : String
   Required : False
   Reference: Addon.Fields
limits
   Type     : String
   Required : False
   Reference: List.Limits
installed
   Type     : string|boolean
   Required : False
   Values   : True,False,all
   Default  : True

===> None are required.

Now executing the actual query:

python kodi_cli.py -H 127.0.0.1 -P 8080 AddOns.GetAddons 

Result:   
{"error":{"code":-32602,"data":{"method":"Addons.GetAddons","stack":{"message":"Received value is null","name":"properties","type":"array"}},"message":"Invalid params."},"id":1,"jsonrpc":"2.0"}.

When I look at the debug-info (-vv) I see that all parameters are passed, regardless if they are specified (or required).

When I request the method manually through command-line like this 
"curl curl -D -  -H 'Content-Type: application/json' 127.0.0.1:8080/jsonrpc -d '{"jsonrpc": "2.0", "id": 1, "method": "AddOns.GetAddons"}'"
I get the correct response,.

**Comment by JavaWiz1** [comment] 2022-08-13 13:19
Sorry, missed this email....  I coded that function, but must not have tested...  I'll take a look and see what the problem is....

Al.
________________________________
From: Ton-O ***@***.***>
Sent: Sunday, July 10, 2022 4:51 AM
To: JavaWiz1/kodi-cli ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [JavaWiz1/kodi-cli] Non-supplied but Non-required fields are still added in call (Issue #1)


Great work, thanks!
I've noticed that the project has knowledge on which fields are optional for a call.
However, the jsonrpc call fails when you do not supply the optional fields.
Example:
See syntax and required fields:
python kodi_cli.py -H 127.0.0.1 -P 8080 AddOns.GetAddons help

————————————————————————————————————————————————————————————————————————————————
Signature : AddOns.GetAddons([type], [content], [enabled], [properties], [limits], [installed])
Description : Gets all available addons
————————————————————————————————————————————————————————————————————————————————
type
Type : String
Required : False
Reference: Addon.Types
Default : unknown
content
Desc : Content provided by the addon. Only considered for plugins and scripts.
Type : String
Required : False
Reference: Addon.Content
Default : unknown
enabled
Type : string|boolean
Required : False
Values : True,False,all
Default : all
properties
Type : String
Required : False
Reference: Addon.Fields
limits
Type : String
Required : False
Reference: List.Limits
installed
Type : string|boolean
Required : False
Values : True,False,all
Default : True

===> None are required.

Now executing the actual query:

python kodi_cli.py -H 127.0.0.1 -P 8080 AddOns.GetAddons

Result:
{"error":{"code":-32602,"data":{"method":"Addons.GetAddons","stack":{"message":"Received value is null","name":"properties","type":"array"}},"message":"Invalid params."},"id":1,"jsonrpc":"2.0"}.

When I look at the debug-info (-vv) I see that all parameters are passed, regardless if they are specified (or required).

When I request the method manually through command-line like this
"curl curl -D - -H 'Content-Type: application/json' 127.0.0.1:8080/jsonrpc -d '{"jsonrpc": "2.0", "id": 1, "method": "AddOns.GetAddons"}'"
I get the correct response,.

**Comment by JavaWiz1** [comment] 2022-08-13 22:13
Ok, call for AddOns.GetAddons has been fixed in v0.1.6.   

I've updated the kodi_namespace.json to default
 properties=[name]
 limits={start=0, end=99}

to call:
kodi-cli AddOns.GetAddons

Will return the list of addons.

**Closed as completed** 2022-08-14 01:06 UTC
